export const UPDATE_SUCCESS_USER = 'UPDATE_SUCCESS_USER';

// Authent:
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';

// Initialize app:
export const CHECK_AUTHENTIFICATION_SUCCESS = 'CHECK_AUTHENTIFICATION_SUCCESS';
export const CHECK_AUTHENTIFICATION_ERROR = 'CHECK_AUTHENTIFICATION_ERROR';
export const FETCH_MY_BLOCKED_PROFILES_SUCCESS = 'FETCH_MY_BLOCKED_PROFILES_SUCCESS';
export const FETCH_MY_BLOCKED_PROFILES_ERROR = 'FETCH_MY_BLOCKED_PROFILES_ERROR';

// Notifications:
export const COUNT_ALL_UNREAD_MESSAGES = 'COUNT_ALL_UNREAD_MESSAGES';
export const COUNT_ALL_NOTSEEN_LIKES = 'COUNT_ALL_NOTSEEN_LIKES';
export const COUNT_ALL_NOTSEEN_VISITORS = 'COUNT_ALL_NOTSEEN_VISITORS';
export const COUNT_ALL_NOTSEEN_REQUESTS = 'COUNT_ALL_NOTSEEN_REQUESTS';
export const COUNT_ALL_NOTSEEN_PRIMARY_NOTIFICATIONS = 'COUNT_ALL_NOTSEEN_PRIMARY_NOTIFICATIONS';

// Realtime data:
export const REALTIME_DATA_NEW_THREAD = 'REALTIME_DATA_NEW_THREAD';
export const REALTIME_DATA_TYPING = 'REALTIME_DATA_TYPING';
export const REALTIME_DATA_NEW_MESSAGE = 'REALTIME_DATA_NEW_MESSAGE';
export const REALTIME_DATA_NEW_LIKE = 'REALTIME_DATA_NEW_LIKE';
export const REALTIME_DATA_NEW_VISIT = 'REALTIME_DATA_NEW_VISIT';
export const REALTIME_DATA_NEW_REQUEST = 'REALTIME_DATA_NEW_REQUEST';
export const REALTIME_DATA_NEW_REQUEST_RESPONSE = 'REALTIME_DATA_NEW_REQUEST_RESPONSE';
export const REALTIME_DATA_NEW_FOLLOW = 'REALTIME_DATA_NEW_FOLLOW';
export const REALTIME_DATA_NEW_BLOCK = 'REALTIME_DATA_NEW_BLOCK';
export const REALTIME_DATA_NEW_PRIMARY_NOTIFICATION = 'REALTIME_DATA_NEW_PRIMARY_NOTIFICATION';

// Cache data:
export const SET_CACHE_DATA_USERS = 'SET_CACHE_DATA_USERS';

// Uploading file:
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const UPDATE_DATA_RELATED_TO_FILE_SUCCESS = 'UPDATE_DATA_RELATED_TO_FILE_SUCCESS';
export const UPDATE_DATA_RELATED_TO_FILE_ERROR = 'UPDATE_DATA_RELATED_TO_FILE_ERROR';

export const DELETE_FILE_SUCCESS = 'DELETE_FILE_SUCCESS';
export const DELETE_FILE_ERROR = 'DELETE_FILE_ERROR';
